---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```


# adstxt

Fraud is a major problem in online advertising. The [ads.txt standard](https://iabtechlab.com/wp-content/uploads/2017/09/IABOpenRTB_Ads.txt_Public_Spec_V1-0-1.pdf) (PDF) allows publishers to add a layer of trust by publishing a list of all ad networks in which they participate. Publishers post a specially formatted text file to domain.com/ads.txt (for example nytimes.com/ads.txt, washingtonpost.com/ads.txt, etc). That file 

## Installation

This package is not available on CRAN. You can install the latest version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("Breza/adstxt")
```
## Usage

The function adstxt() is the heart of the package. Given a URL, it will return a tibble with data from the ads.txt file for that site. If no ads.txt file is found, it will return `NA`.

``` r
nyt <- adstxt("http://nytimes.com")
```

This project is under active development, so feel free to lend a hand! There's a [Contributor Code of Conduct](CODE_OF_CONDUCT.md) to help keep things civil.
